# -*- coding: utf-8 -*-
"""
read the log file generated by the STOMP macro. 
Extract the pixels and time spent of tiles

@author: Bocheng Yin
@Date: 08-01-2019
@Ewald Lab, University of Virginia
"""
"""========================================================"""
import os
files = []
pixelList = []
timeList = []
path = 'G:/Sarah Lab/Data 2019/week July11-Aug17 2019 Toxo STOMP/unprime toxo donut/s3'
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if 'log.txt' in file:
            #files.append(os.path.join(r, file))
            files.append(r)

def readLog(posPath,n):
    posFileName=''.join([posPath,'/log.txt'])   
    text_file = open(posFileName,"r")
    lines = text_file.readlines()
    print(len(lines))
    #print(lines)
    p=[]
    hh=[]
    mm=[]
    ss=[]
    z=0
    
    """
    p for pixels;
    hh for hours of STOMPing time
    mm for minutes of STOMPing time
    ss for seconds of STOMPing time
    z is the tile numbers
    """
    
    import re
    
    def ifWordExist(word,mystring):
        #ignore the case
        pattern = r'(^|[^\w]){}([^\w]|$)'.format(word)
        pattern = re.compile(pattern, re.IGNORECASE)
        matches = re.search(pattern, mystring)
        return bool(matches)
    
    for line in lines:
        if ifWordExist("pixels",line):
            s=re.findall('-?\d*\.?\d+', line)
            #pixel number is the third one in s.
            p.append(float(s[2]))
        elif ifWordExist("elapsed",line):
            s=re.findall('-?\d*\.?\d+', line)
            hh.append(float(s[0]))
            mm.append(float(s[1]))
            ss.append(float(s[2]))
            z+=1
        else:
            continue
        
    text_file.close()
    
    
    """sum up the pixels and photo-bleaching time"""
    def SumTime(hh,mm,ss):
        # return the total hours
        h=sum(hh)
        m=sum(mm)
        s=sum(ss)
        t=h+m/60+s/3600
        return t
     
    pixels = sum(p)
    totalTime = SumTime(hh,mm,ss)
    print('total pixels '+str(n)+' :'+str(pixels)+'\n')
    print('total photo-bleaching time '+str(n)+' :'+str(round(totalTime,2))+' hr\n')
    
    
    import numpy as np
    import pandas as pd
    Len = len(p)
    dA= np.zeros((Len,4))
    dA[:,0]=p
    dA[0:len(hh),1]=hh
    dA[0:len(mm),2]=mm
    dA[0:len(ss),3]=ss
    names=["pixels","hr","min","s"]
    df = pd.DataFrame(dA, index=None, columns=names)
    dfPath = ''.join([posPath,'/df.csv'])
    df.to_csv(dfPath, index=False, header=True,sep=',')
    return pixels,totalTime
# the end of function readLog()
    
i=1
for f in files:
    print(f)
    a,b= readLog(f,i)
    i=i+1
    pixelList.append(a)
    timeList.append(b)
tpixels = sum(pixelList)
tTime = sum(timeList)
print('sum it up')
print('total pixels :'+str(tpixels)+'\n')
print('total photo-bleaching time :'+str(round(tTime,2))+' hr\n')   
